# .goreleaser.yaml
project_name: mr-rogers
before:
  hooks:
    - go mod tidy

# We are back to a single, simple builds section
builds:
  - main: ./mr-rogers.go
    binary: mr-rogers
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

# This archives section now explicitly ignores Windows builds
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ignore:
      - goos: windows

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: mr-rogers
    tap:
      owner: P1NK0
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/P1NK0/mr-rogers"
    description: "Get a friendly quote from Mr. Rogers in your terminal."
    install: |
      bin.install "mr-rogers"