# .goreleaser.yaml
project_name: mr-rogers
before:
  hooks:
    - go mod tidy

# We now have two separate build configurations.
builds:
  # Build group for Linux and macOS
  - id: nix-builds
    main: ./mr-rogers.go
    binary: mr-rogers
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  # Build group specifically for Windows
  - id: windows-builds
    main: ./mr-rogers.go
    binary: mr-rogers
    goos:
      - windows
    goarch:
      - amd64
      - arm64


archives:
  - builds:
      - nix-builds
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: mr-rogers
    tap:
      owner: P1NK0 # <-- IMPORTANT: Change to your GitHub username
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/P1NK0/mr-rogers"
    description: "Get a friendly quote from Mr. Rogers in your terminal."
    install: |
      bin.install "mr-rogers"